#!/usr/bin/env bash
# -e: exit immediately if any command fails, -u: treat unset variables as an error, -o pipefail: the return value of a pipeline is the status of the last command to exit with a non-zero status, or zero if no command exited with a non-zero status. This is sometimes called bash strict mode: https://ewus.de/en/hint/bash-strict-mode
set -euo pipefail

# Reserve nodes immediately after the last job ends, then reboot. This is useful for updating non-exclusive nodes so the node are not blocked while waiting for the last job to end. The reservation is needed to allow backfill to schedule jobs that end before the reboot, but not after. The reservation should be removed by update.sh after the reboot.

# Usage: reserve_reboot "<NODES>" "<REASON>"

DEFAULT_RESERVATION_DURATION="00:02:00"
RESERVATION_NAME_PREFIX="update"

err(){ echo "Error: $*" >&2; exit 1; }
info(){ echo "[info] $*"; }


[[ $# -ge 2 ]] || err "Usage: $0 \"<NODES>\" \"<REASON>\""

NODES_EXPR="$1"
REASON="$2"

# ---------- sanity checks ----------
command -v scontrol >/dev/null 2>&1 || err "scontrol not found"
command -v squeue   >/dev/null 2>&1 || err "squeue not found"
command -v nodeset  >/dev/null 2>&1 || err "nodeset not found"

# Expand node expression -> list of nodes
HOSTLIST=$(nodeset -f "$NODES_EXPR" 2>/dev/null || true)
[[ -n "$HOSTLIST" ]] || err "No nodes matched expression: $NODES_EXPR"
# scontrol show hostnames prints one node per line
readarray -t NODES < <(scontrol show hostnames "$HOSTLIST")

for node in "${NODES[@]}"; do
    info "Processing $node ..."

    endtime=$(squeue -h -w $node -O Endtime | sort | tail -1)

    res_name="${RESERVATION_NAME_PREFIX}-${node}"

    # Create reservation (per node). This lets backfill allow only
    # jobs that finish before start.
    info "  Creating reservation $res_name starting $endtime for node $node"
    scontrol create reservation \
             ReservationName="$res_name" \
             StartTime="$endtime" \
             Duration="$DEFAULT_RESERVATION_DURATION" \
             Nodes="$node" \
             Users=root \
             Flags=MAINT >/dev/null

    # Issue a reboot
    scontrol reboot \
             nextstate=DOWN \
             reason="$REASON" \
             $node >/dev/null

done
