#!/usr/bin/env bash

# Print a simple node status
# Use default time format:
unset SLURM_TIME_FORMAT

nodelist=$*
# Omit the 1st line (timestamp) from sinfo
sinfo -N --long -n $nodelist | tail -n +2
state=`sinfo -h -O StateCompact:4 -n $nodelist`

if [[ "$state" == "idle" ]]
then
	echo
	echo "Node(s) $nodelist have no running jobs"
else
	echo
	echo "Node $nodelist job information:"
	squeue -O JobID:10,NumNodes:6,Partition:15,UserName:12,StartTime,EndTime,NodeList:50 -w $nodelist
fi

# Check if squeue returned without error
if [[ "$?" == 0 ]]
then
	echo
	echo "NODE CONFIGURATION:"
	scontrol show node $nodelist
fi

# Show recent node events

# Default period of start of events is 00:00:00 of the previous day, but this can be changed with the Start= option.
# Example event start times:
EventStart=""
# EventStart=Start=now-4weeks
# EventStart=All_Time

echo "NODE EVENTS:"
sacctmgr show event $EventStart Format=NodeName,TimeStart,Duration,State%-6,Reason%-40 where nodes=$nodelist
