#!/usr/bin/env bash

# Slurm: use scontrol to manage nodes
# Note: This only works with nodes in Slurm power saving, NOT nodes in state DOWN, DRAIN etc.
# Homepage: https://github.com/OleHolmNielsen/Slurm_tools/

# Check if Slurmpower saving has been configured
suspendprogram=`scontrol show config | grep SuspendProgram | awk '{print $3}'`
if [[ $suspendprogram == "(null)" ]]
then
	echo "ERROR: Slurm SuspendProgram is not configured"
	exit 1
fi

NODES="$1"
ACTION="down"
statelist="idle"	# Only these Slum states are eligible for power saving

if [[ $# -ne 1 ]]
then
	echo "Usage: $0 nodename-list"
	exit 1
fi

# Check the node list
if [[ "`sinfo -t $statelist -hN -n $NODES`" = "" ]]
then
	echo "ERROR: Nodes $NODES are not idle or do not exist"
	exit 1
fi

echo "Slurm action=power $ACTION on nodes $NODES"
# Obsolete since 24.05:
# /usr/bin/scontrol update nodename=$NODES state=$ACTION
/usr/bin/scontrol power $ACTION $NODES
/usr/bin/sinfo -N -n $NODES
