#!/usr/bin/env bash

# Slurm: use scontrol to manage nodes
# Note: This only works with nodes in Slurm power saving, NOT nodes in state DOWN, DRAIN etc.
# Homepage: https://github.com/OleHolmNielsen/Slurm_tools/

NODES="$1"
ACTION="down"

if [[ $# -ne 1 ]]
then
	echo "Usage: $0 nodename-list"
	exit 1
fi

# Check the node list
if [[ "`sinfo -hN -n $NODES`" = "" ]]
then
	echo "ERROR: Nodelist $NODES does not exist"
	exit 1
fi

echo "Action=$ACTION on nodes $NODES"
# Obsolete since 24.05:
# /usr/bin/scontrol update nodename=$NODES state=$ACTION
/usr/bin/scontrol power $ACTION $NODES
/usr/bin/sinfo -N -n $NODES
