#!/usr/bin/env bash

# Print the Slurm version on a nodelist.
# Usage: sversion node-list
# Requires ClusterShell, see https://clustershell.readthedocs.io/en/latest/intro.html
# Homepage: https://github.com/OleHolmNielsen/Slurm_tools/

clush -b -w $@ slurmd -V
