#!/usr/bin/env bash

# Slurm: Add nice level to jobs, or list jobs with non-zero nice level.
# Requires also the helper script "joblist".
# Homepage: https://github.com/OleHolmNielsen/Slurm_tools/

function usage()
{
	cat <<EOF
Usage:
Listing:
$0 -l | -p partition [-u username]
Setting:
$0 [-d] [-n nice-value] [-f jobfile | -u username [ -p partition] | job [,jobs...] ]
where:
* -n is the Slurm job Nice value
* -f is a file with jobids
* -u is a username
* -p is a partition name
* -d means "dry run" (do nothing)
Jobs should be comma or space separated.
EOF
}

# Requires the helper script "joblist".
JOBLISTFORMAT=`which joblist`
if [[ $? -ne 0 ]]
then
	echo "ERROR: The joblist script cannot be found"
	exit 1
fi

# Dry run (do nothing)
dryrun=0
# Select a user:
userselect=""
# List or set nice values:
listnice=0
# Default nice value
NICE=-50000
SQUEUE_FORMAT=Nice,PriorityLong,State,JobID,Partition,UserName,GroupName,StartTime,EndTime,Name,tres-per-node,Reason

# Parse command options
while getopts "dlp:n:f:u:h" options; do
	case $options in
		d )	dryrun=1
			echo "Make a dry run only"
			;;
		l )	listnice=1
			;;
		n )	NICE=$OPTARG
			echo "Set job nice value to $NICE"
			;;
		u )	userselect="-u $OPTARG"
			echo "Select jobs of user $OPTARG"
			;;
		p )	partition="-p $OPTARG"
			echo "Select partition $OPTARG"
			;;
		f )	JOBFILE=$OPTARG
			if [[ ! -s "$JOBFILE" ]]
			then
				echo "File $JOBFILE is not a regular file or is empty"
				exit 1
			fi
			echo "Append jobid list from file $JOBFILE"
			;;
		h | * )	usage
			exit 1;;
	esac
done
shift $((OPTIND-1))

JOBLIST="$*"

if [[ -n "$JOBFILE" ]]
then
	# Sanity check of JOBFILE
	JOBLIST="`$JOBLISTFORMAT -f $JOBFILE`"
	if [[ $? -ne 0 ]]
	then
		echo "The $JOBLISTFORMAT script returned an error on this job list:"
		echo "$JOBLIST"
		usage
		exit 1
	fi
	echo "JOBLIST=$JOBLIST"
# Remaining arguments should be a job list (ignore if username is set)
elif [[ -z "$userselect" && $# -gt 0 ]]
then
	# Sanity check of JOBLIST
	JOBLIST="`$JOBLISTFORMAT $JOBLIST`"
	if [[ $? -ne 0 ]]
	then
		echo "The $JOBLISTFORMAT script returned an error on this job list:"
		echo "$JOBLIST"
		usage
		exit 1
	fi
	echo "JOBLIST=$JOBLIST"
fi

if [[ $listnice -eq 0 ]]
then
	if [[ -n "$userselect" ]]
	then
		# Update jobs of a username and optionally partition (ignore job list arguments)
		JOBFILE=`mktemp`
		squeue $userselect $partition -t Pending -O JobID -h > $JOBFILE
		JOBLIST="`$JOBLISTFORMAT -f $JOBFILE`"
		rm -f $JOBFILE
	elif [[ -n "$partition" ]]
	then
		# It would make no sense to increase the nice value for all jobs in a partition
		echo "ERROR: The partition name must be specified together with a username"
		usage
		exit 1
	fi
	# Change nice level of jobs and print a status
	if [[ $dryrun -eq 0 ]]
	then
		scontrol update jobid=$JOBLIST nice=$NICE
	fi
	squeue $userselect $partition -O "$SQUEUE_FORMAT" -j $JOBLIST
else
	# Just print a listing
	echo; echo "Jobs with a non-zero nice value:"; echo
	squeue $userselect $partition -O "$SQUEUE_FORMAT" | awk '{if ($1 != 0) print $0}' 
fi


# Read the bf_min_prio_reserve scheduler parameter (see 'man slurm.conf').
cat <<EOF

Note: The backfill and main scheduling logic will not reserve resources for pending jobs
unless they have a priority equal to or higher than the bf_min_prio_reserve.

EOF

scontrol show config | grep SchedulerParameters | awk '
{
	bf_min_prio_reserve="bf_min_prio_reserve is undefined"
	split($3,array,",")
	for (i in array) {
		if (array[i] ~ "bf_min_prio_reserve") bf_min_prio_reserve=array[i]
	}
} END {
	print "The SchedulerParameters in slurm.conf currently contain: " bf_min_prio_reserve
}'
