#!/bin/sh

# Print a warning about bad jobs hanging indefinitely in the queue.

# This script may be run regularly from crontab

# List of Job Reason Codes (see "man squeue") which we look for
export REASONLIST="BadConstraints|InvalidAccount|InvalidQOS|JobLaunchFailure|NodeDown|PartitionDown|PartitionInactive|PartitionNodeLimit|PartitionTimeLimit|ReqNodeNotAvail|WaitingForScheduling|JobHoldMaxRequeue"

# Configure the columns printed by squeue
export SQUEUE_FORMAT="%.18i %.9P %.8j %.8u %.8a %.10T %.9Q %.10M %.9l %.6D %.6C %m %R"

squeue | egrep "$REASONLIST"
