#!/usr/bin/env bash

# Slurm batch queue: Show list of reasons for pending jobs
# Only job reasons other than "Priority", "Resources" and "Dependency" are shown.
# Options such as "-p partition" etc. are passed to the squeue command:

squeue $@ -h -t pending -O "Username,Account,Partition,MaxCPUs,MaxNodes,Reason: " | sort | uniq -c | awk '
BEGIN {
	# Collect partition information using "showpartitions" from this project
	while (("showpartitions -n" | getline) > 0) {
		p = $1
		len = length(p)         # Length of partition name string
		if (len > plen) plen = len    # Calculate maximum string length
		nodes[p] = $3
		idlenodes[p] = $4
		cores[p] = $5
		idlecores[p] = $6
	}
	fmt="%8s %8s \t%12s\t%-16s %5s %5s %5s %5s %5s\n"
	printf(fmt, "User", "Account", "Partition", "Reason", "#Jobs", "Nodes", "Idle", "Cpus", "Idle")
}
{
	jobcount=$1	# The jobcount comes from "uniq -c"
	username=$2
	account=$3
	p=$4		# Partition name
	numcpus=$5
	numnodes=$6
	reason=$7
	if (reason !~ "Priority" && reason !~ "Resources" && reason !~ "Dependency") {
		printf(fmt,
			username, account, p, reason, jobcount, numnodes*jobcount, idlenodes[p], numcpus*jobcount, idlecores[p])
	}
}'
