#!/usr/bin/env bash

# Show list of Slurm reasons for jobs that are in a pending state.
# Only job reasons other than "Priority", "Resources" and "Dependency" are shown.
# Any command options such as "-p partition" are added to the squeue command.
# Author: Ole.H.Nielsen@fysik.dtu.dk
# Homepage: https://github.com/OleHolmNielsen/Slurm_tools/

# Usage: showjobreasons [squeue-options]

squeue $@ -h -t pending -O "Username,Account,Partition: ,MaxCPUs,MaxNodes,Reason: " | sort | uniq -c | awk '
BEGIN {
	# Collect partition information using the "showpartitions" script from this project
	while (("showpartitions -n" | getline) > 0) {
		p = $1	# Partition name
		len = length(p)	 # Length of partition name string
		if (len > plen) plen = len    # Calculate maximum string length
		nodes[p] = $3
		idlenodes[p] = $4
		cores[p] = $5
		idlecores[p] = $6
	}
	fmt="%8s %8s \t%12.12s\t%-27.27s %5s %5s %5s %5s %5s %s\n"
	printf(fmt, "User", "Account", "Partition", "Reason", "#Jobs", "Nodes", "Idle", "Cpus", "Idle", "Full-name")
}
{
	jobcount=$1	# The jobcount comes from "uniq -c"
	username=$2
	account=$3
	p=$4
	numcpus=$5
	numnodes=$6
	reason=$7
	if (reason !~ "Priority" && reason !~ "Resources" && reason !~ "Dependency") {
		# First get the user full name
		COMMAND="getent passwd " username
		COMMAND | getline
		split($0,b,":")	 # Full name b[5] of this username (b[1])
		close(COMMAND)
		printf(fmt, username, account, p, reason, jobcount,
			numnodes*jobcount, idlenodes[p], numcpus*jobcount, idlecores[p], b[5])
	}
}'
