#!/bin/sh

# Select this user by default:
SELECT="user=$USER"

#
# Command usage:
#
function usage()
{
        cat <<EOF
Usage: $0 [-u username | -a | -h ]
where:
        -u username: Print only user <username> 
        -a Print all users
        -h Print help information
EOF
}


#
# Parse command options
#

while getopts "u:ah" options; do
case $options in
	u ) SELECT="user=$OPTARG"	# Select this user
	    ;;
	a ) SELECT=""	# All users
	    ;;
	h|*|? ) usage
	    exit 1;;
esac
done

# Test for extraneous command line arguments
if test $# -gt $(($OPTIND-1))
then
	echo ERROR: Too many command line arguments: $*
	usage
	exit 1
fi

echo
echo Slurm associations limits:
echo

# sacctmgr show associations format (non-default) adding GrpJobsAccrue,MaxJobsAccrue
# Default format: Cluster|Account|User|Partition|Share|GrpJobs|GrpTRES|GrpSubmit|GrpWall|GrpTRESMins|MaxJobs|MaxTRES|MaxTRESPerNode|MaxSubmit|MaxWall|MaxTRESMins|QOS|Def QOS|GrpTRESRunMins|
# See "man acctmgr" section "LIST/SHOW ASSOCIATION FORMAT OPTIONS"
export fmt="Cluster,Account,User,Partition,Fairshare,GrpJobs,GrpTRES,GrpSubmit,GrpWall,GrpTRESMins,MaxJobs,MaxTRES,MaxTRESPerNode,MaxSubmit,MaxWall,MaxTRESMins,QOS,DefaultQOS,GrpTRESRunMins,GrpJobsAccrue,MaxJobsAccrue"

sacctmgr -rp show associations $SELECT format=$fmt | awk '-F|' '
{
if (NR==1) {
	split($0,header,"|")
} else {
	split($0,assoc,"|")
	if (length(assoc[3]) == 0) next	# Skip non-user accounts
	if (length(assoc[4]) == 0) assoc[4] = "(any)"
	printf("Association: User=%s Account=%s Cluster=%s Partition=%s\n",
		assoc[3], assoc[2], assoc[1], assoc[4])
	for (i=5; i<length(assoc); i++)
		if (length(assoc[i]) > 0)
			printf("%20s: %s\n", header[i], assoc[i])
	}
}'
