#!/bin/sh

# Manage Slurm user fairshare, QOS and limits:
# Create, update or delete Slurm user accounts from the passwd file.
# Update the fairshare, QOS and limits configurations.

# Run commands remotely if your Slurm host does not have gawk version 4:
# Execute commands on a remote host by password-less SSH:
# export remote="ssh <slurm-host>"

# Skip users with UID < MINUID
export MINUID=1002

# FairShare configuration:
# See https://slurm.schedmd.com/fair_tree.html
# and https://slurm.schedmd.com/priority_multifactor.html
# User fairshares may be defined from several sources prioritized as follows:
# 1. UNIX-group fairshares defined in the user_settings_conf file
# 2. Inherited from Slurm (non-user) accounts.
# 3. A default value set by fairshare.
# Set a default user Fairshare:
# export fairshare="parent"
export fairshare="2"

# Resource limits configuration 
# See https://slurm.schedmd.com/resource_limits.html
# Our global default user TRES parameters:
export GrpTRES="cpu=1500"
export GrpTRESRunMins="cpu=3000000"
# If you want to clear these values use -1:
# export GrpTRES="cpu=-1"
# export GrpTRESRunMins="cpu=-1"

# Slurm commands
export sacctmgr=/usr/bin/sacctmgr

# User settings configuration file:
export user_settings_conf=/etc/slurm/user_settings.conf
if test ! -f $user_settings_conf
then
	echo "### WARNING : No account settings configuration file $user_settings_conf"
fi

# WARNING: GNU gawk version 4.0 or later is required for arrays of arrays
awk_version=`awk --version | head -1 | awk '{version=$3; split(version,v,"."); print v[1]}'`
if test "$awk_version" = "3"
then
	echo -n "Sorry, gawk version 4.0 or later is required.  Your version is: "
	awk --version | head -1
	exit 1
fi

# Print a header
cat <<EOF
###
### Create, update or delete Slurm users in the database from passwd file $PASSWD
### Users are created under the same account name as their Groupname (GID).
### Minimum UID considered is $MINUID.
### Account settings configuration file for UNIX groups is 
### `ls -l $user_settings_conf`
###
EOF

# Process all users in the system passwd database

# We have to store data in temporary files because remote ssh in 
# the awk BEGIN section apparently breaks awk.
export passwd_tmp="/tmp/passwd.$$"
export group_tmp="/tmp/group.$$"
export assoc_tmp="/tmp/assoc.$$"
export users_tmp="/tmp/users.$$"
$remote getent passwd > $passwd_tmp
$remote getent group > $group_tmp
 
# sacctmgr show associations format (non-default) adding GrpJobsAccrue,MaxJobsAccrue
# Default format: Cluster|Account|User|Partition|Share|GrpJobs|GrpTRES|GrpSubmit|GrpWall|GrpTRESMins|MaxJobs|MaxTRES|MaxTRESPerNode|MaxSubmit|MaxWall|MaxTRESMins|QOS|Def QOS|GrpTRESRunMins|
# See "man acctmgr" section "LIST/SHOW ASSOCIATION FORMAT OPTIONS"
assocfmt="Cluster,Account,User,Partition,Fairshare,GrpJobs,GrpTRES,GrpSubmit,GrpWall,GrpTRESMins,MaxJobs,MaxTRES,MaxTRESPerNode,MaxSubmit,MaxWall,MaxTRESMins,QOS,DefaultQOS,GrpTRESRunMins,GrpJobsAccrue,MaxJobsAccrue"
$remote sacctmgr -snorp show associations format=$assocfmt > $assoc_tmp
# Format for users:
userfmt="User,DefaultAccount,Account,Cluster"
$remote sacctmgr -nrp show user WithAssoc format=$userfmt > $users_tmp

cat $passwd_tmp | gawk -F: '
BEGIN {
        MINUID = ENVIRON["MINUID"]
	user_settings_conf = ENVIRON["user_settings_conf"]
	sacctmgr = ENVIRON["sacctmgr"]
        passwd	= ENVIRON["passwd_tmp"]
        group	= ENVIRON["group_tmp"]
        assoc	= ENVIRON["assoc_tmp"]
        users	= ENVIRON["users_tmp"]
	debug = 0	# Debugging flag

	IGNORECASE = 1	# Make case-insensitive string comparisons (for TRES comparisons)

	# Default settings defined in this script above (fallback values)
	defaults["fairshare"]		= ENVIRON["fairshare"]
	defaults["GrpTRES"]		= ENVIRON["GrpTRES"]
	defaults["GrpTRESRunMins"]	= ENVIRON["GrpTRESRunMins"]

	# Create an array of Slurm factors (slurm_factors)
	string = "fairshare GrpTRES GrpTRESMins MaxTRES MaxTRESPerNode MaxTRESMins GrpTRESRunMins QOS DefaultQOS GrpJobsAccrue MaxJobsAccrue"
	split(string, slurm_factors, " ")

	# Define index values of the setting[] array
	config = 1; current = 2

	# Get the list of UNIX group names from the system by getent(1)
	FS=":"	# Set the Field Separator
	while ((getline < group) > 0) {
		split($0,b,":")	 # Split group line into fields
		b[1] = tolower(b[1])	# Make it lowercase
		unixgroup[b[3]] = b[1]	# Group name b[1] of this GID (b[3])
		groupname[b[1]] = b[1]	# Group name b[1]
	}
	close (group)

	# Set the Field Separator to | for the parseable account list
	FS="|"

	# Read list of existing users and their default account (parseable output)
	# Header of sacctmgr -nrp show user: See the "userfmt" variable above.
	while ((getline < users) > 0) {
		if (debug > 1) print "Got user " $0
		u = $1	# User
		d = $2	# Default Account
		a = $3	# Account
		c = $4	# Cluster
		if (u != "root") {
			defaultaccount[u] = d
			if (a != d) useraccounts[u][a] = a	# Record non-default accounts for this user
		}
	}
	close (users)

	# Read list of existing accounts (parseable output)
	# Header of sacctmgr -snorp show associations: See the "assocfmt" variable above.
	while ((getline < assoc) > 0) {
		if (debug > 1) print "Got account " $0
		a = $2	# account
		u = $3	# user
		if (a == "root") continue	# Skip the root account
		if (u == "") {
			if (groupname[a] == "") {	# Non-existent group
				if (debug > 0) print "### NOTICE: UNIX group " a " does not exist"
				continue	# Skip it
			}
			item = a	# Not a user account: UNIX group 
		} else {
			item = u	# User account
			user[u]		= u
			if (defaultaccount[u] == "") {
				print "### NOTICE: No default account for user " u ", setting it to ", a
				defaultaccount[u] = a
			}
			useraccount[u]	= defaultaccount[u]
			if (debug > 1 && a != defaultaccount[u])
				print "### NOTICE: Default account for user " u "=" useraccount[u] ", cannot set it to " a
		}
		# Record the user/group settings
		setting[item][current]["fairshare"]	= $5
		setting[item][current]["GrpJobs"]	= $6
		setting[item][current]["GrpTRES"]	= tolower($7)	# cpu= must be in lowercase
		setting[item][current]["GrpSubmit"]	= $8
		setting[item][current]["GrpWall"]	= $9
		setting[item][current]["GrpTRESMins"]	= $10
		setting[item][current]["MaxJobs"]	= $11
		setting[item][current]["MaxTRES"]	= $12
		setting[item][current]["MaxTRESPerNode"]= $13
		setting[item][current]["MaxSubmitJobs"]	= $14
		setting[item][current]["MaxWall"]	= $15
		setting[item][current]["MaxTRESMins"]	= $16
		setting[item][current]["QOS"]		= toupper($17)
		setting[item][current]["DefaultQOS"]	= toupper($18)
		setting[item][current]["GrpTRESRunMins"]= tolower($19)	# cpu= must be in lowercase
		setting[item][current]["GrpJobsAccrue"]	= $20
		setting[item][current]["MaxJobsAccrue"]	= $21
	}
	close (assoc)

	#
	# Read the account settings configuration file: user_settings_conf
	#
	FS=":"	# Set the Field Separator

	# Syntax of this file is 3 items separated by ":"
	# [DEFAULT|UNIX_group|username]:[Type]:value
	# Type may be: fairshare, GrpTRES, GrpTRESRunMins, etc.

	while ((getline < user_settings_conf) > 0) {
		if (index($1,"#") >= 1) continue	# Skip lines with # comments
		if (NF != 3) continue			# Skip lines which do not have 3 fields (incl. empty lines)
		for (f in slurm_factors) if (tolower($2) == tolower(slurm_factors[f])) $2 = slurm_factors[f]	# Force correct spelling of $2
		if ($1 == "DEFAULT") {			# Default value
			defaults[$2] = $3
		} else if (groupname[$1] == "") {	# Unknown UNIX group: Assume that $1 is a username
			if (useraccount[$1] == "") print "### NOTICE: Slurm account in user_settings_conf for group/user " $1 " is unknown"
			setting[$1][config][$2] = $3
		} else {				# UNIX group value
			setting[$1][config][$2] = $3
		}
	}
	close (user_settings_conf)
	if (debug > 0) print "### End of BEGIN section"
}

#
# Process password file entries
#
$3 < MINUID { if (debug > 0) print "Skip user " $1 " with UID=" $3 }	# Skip users with UID < MINUID
$3 >= MINUID {
	u		= $1
	GID		= $4
	FULLNAME	= $5
	HOMEDIR		= $6
	SHELL		= $7
	if (SHELL == "/sbin/nologin") next	# Skip non-login users
	g = unixgroup[GID]	# UNIX group
	if (debug > 0) print "User " u " group " g 
	# Check the user UNIX account
	if (g == "") {
		printf("### ERROR: User %s GID %d has no GROUPNAME\n", u, GID)
		next
	}
	# Check that the UNIX group exists as a Slurm account
	if (!isarray(setting[g])) {
		printf("### WARNING for user %s: The UNIX group %s has no corresponding Slurm account\n", u, g)
		next
	}
	# Check for existence of the user home directory, skip user if absent:
	if (system("test -d \""HOMEDIR"\"") != 0) {
		if (debug > 0) printf("### Skipping user %s because homedir %s does not exist\n", u, HOMEDIR)
		nohomedir[u] = HOMEDIR	# Record users with no available homedir
		next
	}
	userexists[u] = u	# Record existing users

	# Gather arguments for the sacctmgr command
	COMMAND = ""		# We are going to append a number of variables to COMMAND below

	# Adding a user to an existing account
	if (debug > 0) printf("### User %s exists under account=%s fairshare=%s\n", u, useraccount[u], setting[u][current]["fairshare"])
	if (useraccount[u] != g) {
		printf("### NOTICE: User %s has default account=%s, add to new default account=%s (primary UNIX group)\n", u, defaultaccount[u], g)
		COMMAND = COMMAND " defaultaccount=" g
		# Add already existing user to his/her new account
		if (useraccount[u] != "")
			print sacctmgr " -i add user " u " account=" g
	}

	# Loop over the setting[] array and configure any changes

	# If user setting not explicitly given, then use the group setting
	if (isarray(setting[g][config])) {
		for (i in setting[g][config]) {
			if (setting[u][config][i] == "") setting[u][config][i] = setting[g][config][i]
		}
	} else {
		print "### NOTICE: Group " g " has no settings, using default values for user " u
	}
	# If user setting not explicitly given, then use the default setting
	for (i in defaults) {
		if (setting[u][config][i] == "") setting[u][config][i] = defaults[i]
	}
	# Compare config and current settings, print out any changes
	for (i in setting[u][config]) {
		if (debug > 0) print "# User " u " current " i "=" setting[u][current][i] " config " setting[u][config][i]
		if (setting[u][current][i] != setting[u][config][i]) {
			if (setting[u][current][i] != "")
				print "# User " u " currently has " i "=" setting[u][current][i] " but configuration is " setting[u][config][i]
			COMMAND = COMMAND " " i "=" setting[u][config][i]
		}
	}

	if (user[u] != "") {
		# Modify existing user
		if (COMMAND != "")
			print sacctmgr " -i modify user where name=" u " set" COMMAND
	} else {
		# New user: command for creating this account
		print sacctmgr " -i create user name=" u COMMAND
	}
}
END {
	# Check for accounts belonging to non-existent users
	for (u in user) {
		if (userexists[u] != "") continue
		if (nohomedir[u] != "") 
			printf("### Slurm account %s has no available home directory %s\n", u, nohomedir[u])
		else
			printf("### Slurm account %s has no user entry in the passwd file\n", u)
		# First delete non-default accounts for this user
		for (a in useraccounts[u])
			print sacctmgr " -i delete user " u " account=" useraccounts[u][a]
		# The delete the user
		print sacctmgr " -i delete user " u
	}
}'

# Clean-up
rm -f $passwd_tmp $group_tmp $assoc_tmp $users_tmp
