#!/usr/bin/env bash

# Make Slurm cluster usage statistics
# Usage: topreports [period-see-below]
# Default periods: last-month ("") current-month (-c) current-week (-w)

# Author:       Ole.H.Nielsen@fysik.dtu.dk
# Homepage: https://github.com/OleHolmNielsen/Slurm_tools/

# CONFIGURE THIS: 
# Directory name and report file name prefix:
PREFIX=/TOPDIR/Top
# Partion list: overlapping partitions are comma-separated so they will be reported together
partitionlist="xeon24,xeon24el8,xeon24el8_512,xeon24el8_test xeon32_4096 xeon40,xeon40_768,xeon40_clx,xeon40el8 xeon56,xeon56cmr sm3090,sm3090_768,sm3090el8,sm3090el8_768,sm3090_devel epyc96 a100,a100_week xeon32_4096,xeon32_week"
# END CONFIGURE

slurmacct=slurmacct

if test $# -eq 0
then
	# Default periods: last-month ("") current-month (-c) current-week (-w) current-year (-y)
	periods="None -c -w -y"
else
	# Select month and year (like "november2019")
	periods="-m$1"
fi

# The empty string selects the default period (last month)
for period in $periods
do
	echo "================================================"
	echo
	echo Generating reports for period=$period
	echo
	if test "$period" = "None"
	then
		period=""
	fi
	# The empty string selects all partitions in the cluster
	for p in "" $partitionlist
	do
		if test -z "$p"
		then
			name="."
			partition=""
		else
			name=`echo $p | cut -f1 -d,`	# Select first field in a,b,...
			name=."$name."
			partition="-p $p"
		fi
		echo
		echo Generating report for partition=$partition and period=$period
		echo Group report
		$slurmacct -G $partition $period -r $PREFIX$name	# Group report
		echo User report
		$slurmacct -n $partition $period -r $PREFIX$name	# Append user report
	done
done
