#!/usr/bin/env bash

# Make Slurm cluster usage statistics for specified periods, using slurmacct

# Command usage:
function usage()
{
        cat <<EOF
Usage: $0 [-m monthyear] | -Y yyyy ] [-r report-prefix] [-h]
where:
        -m: Select periods: month and year (like "november2024"), see slurmacct
	    Default periods: last-month, current-month, current-week, and current-year 
	-Y: Select an entire year yyyy (like 2025)
	-r: Report name prefix (Default PREFIX=/tmp/Top)
        -h: Print this help information
EOF
}

# Author:       Ole.H.Nielsen@fysik.dtu.dk
# Homepage: https://github.com/OleHolmNielsen/Slurm_tools/

# CONFIGURE THIS: 
# Directory name and report file name prefix:
# PREFIX=<top-directory-name>/Top
# Partion list: overlapping partitions are comma-separated so they will be reported together
PREFIX=/tmp/Top
# Partion list: overlapping partitions are comma-separated so they will be reported together
partitionlist="xeon24el8,xeon24el8_512,xeon24el8_test,xeon24 xeon32_4096,xeon32_week xeon40el8,xeon40el8_768,xeon40el8_clx,xeon40 xeon56,xeon56cmr sm3090el8,sm3090el8_768,sm3090_devel,sm3090 epyc96 a100,a100_week h200,h200_week"
# END CONFIGURE

# Default periods: last-month ("") current-month (-c) current-week (-w) current-year (-y)
periods="Default -c -w -y"

export PATH=$PATH:/usr/local/bin:/usr/local/sbin
export TIMEFORMAT=' - Time: %R seconds'

# Process options
while getopts "m:Y:r:h" options; do
        case $options in
                m )     periods="-m"
			monthyear="$OPTARG"
                        ;;
                Y )     periods="-Y"
			selectyear="$OPTARG"
			if [[ $selectyear -lt 2010 || $selectyear -gt 2040 ]]
			then
				echo "Please select a year in the range 2010..2040"
				usage
				exit 1
			fi
                        ;;
		r )     export PREFIX="$OPTARG"
                        echo " - Report prefix: $OPTARG"
                        ;;
                h|? ) usage
                        exit 1;;
                * ) usage
                        exit 1;;
        esac
done
shift $((OPTIND-1))

# A separator line
line="--------------------------------------------------------------------------------"

# The empty string selects the default period (last month) in slurmacct
for period in $periods
do
	pp="$period"		# Period argument $pp to slurmacct
	ppnice="$period"	# Nice string for printing
	if [[ "$period" == "Default" ]]
	then
		pp=""
		ppnice="Last month"
	elif [[ "$period" == "-c" ]]
	then
		ppnice="Current month"
	elif [[ "$period" == "-w" ]]
	then
		ppnice="Current week"
	elif [[ "$period" == "-y" ]]
	then
		ppnice="Current year"
	elif [[ "$period" == "-m" ]]
	then
		pp="-m $monthyear"
		ppnice="The month/year $monthyear"
	elif [[ "$period" == "-Y" ]]
	then
		pp="-Y $selectyear"
		ppnice="The year $selectyear"
	fi
	# Adding the empty string "" selects all partitions in the cluster:
	for p in "" $partitionlist
	do
		TRESGPU=0
		displaypart="partition=$p"
		if [[ "$p" == "" ]]
		then
			name="."
			partition=""
			displaypart="ALL partitions"
		else
			name=`echo $p | cut -f1 -d,`	# Select first field in a,b,...
			name=."$name."
			partition="-p $p"
			# Determine if one or more partitions in the list $p has TRES GPU resources
			for i in ${p//,/ }	# Split $p into separate words
			do
				if [[ "`scontrol show partitions $i | grep TRES | grep gres/gpu`" != "" ]]
				then
					TRESGPU=1
				fi
			done
		fi
		cat << EOF
$line
	
Generating reports for $displaypart (report name=$name) during period: $ppnice
	
$line
EOF

		header=""	# If $header is empty a new report will be generated
		if [[ $TRESGPU == 1 ]]
		then
			echo
			echo "PARENT GROUP TRES GPU report for partitions $p"
			time slurmacct -P $header -T $partition $pp -r $PREFIX$name	# TRES GPU Group report
			header="-n"	# No header will append to the next report
			echo
			echo "GROUP TRES GPU report for partitions $p"
			time slurmacct -G $header -T $partition $pp -r $PREFIX$name	# TRES GPU Group report
			echo
			echo "USER TRES GPU report for partitions $p"
			time slurmacct $header -T $partition $pp -r $PREFIX$name	# TRES GPU report
		fi
		echo
		echo "PARENT GROUP CPUs report for partitions $p"
		time slurmacct -P $header -C $partition $pp -r $PREFIX$name	# Group report
		header="-n"	# No header will append to the next report
		echo
		echo "GROUP CPUs report for partitions $p"
		time slurmacct -G $header -C $partition $pp -r $PREFIX$name	# Group report
		echo
		echo "USER CPUs report for partitions $p"
		time slurmacct $header -C $partition $pp -r $PREFIX$name	# Append user report
	done
done
